id: P000344
initial_creation_type: ocr
created_at: 14/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG14787
  title: མངོན་བརྗོད་རྒྱ་མཚོའི་ཆུ་ཐིགས་ཀྱི་འགྲེལ་པ་བྱིས་པའི་འཇུག་ངོགས།
  author: ''
  volumes:
    5c6a8c136455466ab2468ae2c0aa8964:
      image_group_id: I1KG14833
      title: Volume 1 of mngon brjod rgya mtsho'i chu thigs kyi 'grel pa byis pa'i
        'jug ngogs/
      volume_number: 1
      total_pages: 378
      base_file: v001.txt
