id: opecha:P000344
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG14787
  title: མངོན་བརྗོད་རྒྱ་མཚོའི་ཆུ་ཐིགས་ཀྱི་འགྲེལ་པ་བྱིས་པའི་འཇུག་ངོགས།
  volume:
    5c6a8c136455466ab2468ae2c0aa8964:
      image_group_id: I1KG14833
      title: Volume 1 of mngon brjod rgya mtsho'i chu thigs kyi 'grel pa byis pa'i
        'jug ngogs/
      volume_number: 1
      total_pages: 378
  author: ''
ebook_metadata:
  title: མངོན་བརྗོད་རྒྱ་མཚོའི་ཆུ་ཐིགས་ཀྱི་འགྲེལ་པ་བྱིས་པའི་འཇུག་ངོགས།
  author: ''
  sku: P000344
  cover: cover.jpg
  layers:
  - pagination
