id: I04CA0E90
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-14T09:48:54+00:00'
last_modified: '2022-06-10T04:45:00.051720+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG14787
  title: མངོན་བརྗོད་རྒྱ་མཚོའི་ཆུ་ཐིགས་ཀྱི་འགྲེལ་པ་བྱིས་པའི་འཇུག་ངོགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    D8FD:
      image_group_id: I1KG14833
      title: Volume 1 of mngon brjod rgya mtsho'i chu thigs kyi 'grel pa byis pa'i
        'jug ngogs/
      total_pages: 378
      order: 1
      base_file: D8FD.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
